*Q1*

In [32]:
import spacy
from spacy import displacy
import fitz
import re

pdf_file_path = '/content/PALESTINE.pdf'
target_word = 'palestine'

pdf_document = fitz.open(pdf_file_path)

word_count = 0

for page_num in range(pdf_document.page_count):
    page = pdf_document[page_num]
    text = page.get_text()

    occurrences = re.findall(r'\b{}\b'.format(re.escape(target_word)), text, re.IGNORECASE)

    word_count += len(occurrences)

pdf_document.close()

print("Word count for '{}': {}".format(target_word, word_count))


Word count for 'palestine': 16


**Q2**

In [11]:
pdf_document = fitz.open(pdf_file_path)
for page_num in range(pdf_document.page_count):
    page = pdf_document[page_num]
    text = page.get_text()

    paragraphs = text.split('\n')


    paragraphs = [p for p in paragraphs if p.strip()]

    print(f"Page {page_num + 1}: {len(paragraphs)} paragraphs\n")


pdf_document.close()


Page 1: 20 paragraphs

Page 2: 42 paragraphs

Page 3: 42 paragraphs

Page 4: 41 paragraphs

Page 5: 35 paragraphs

Page 6: 37 paragraphs

Page 7: 39 paragraphs

Page 8: 38 paragraphs

Page 9: 34 paragraphs

Page 10: 35 paragraphs

Page 11: 33 paragraphs

Page 12: 36 paragraphs

Page 13: 30 paragraphs

Page 14: 37 paragraphs

Page 15: 35 paragraphs

Page 16: 39 paragraphs

Page 17: 37 paragraphs

Page 18: 38 paragraphs

Page 19: 37 paragraphs

Page 20: 38 paragraphs

Page 21: 33 paragraphs

Page 22: 31 paragraphs

Page 23: 35 paragraphs

Page 24: 36 paragraphs

Page 25: 39 paragraphs

Page 26: 3 paragraphs

Page 27: 39 paragraphs

Page 28: 33 paragraphs

Page 29: 34 paragraphs

Page 30: 18 paragraphs



In [21]:
import fitz

pdf_document = fitz.open(pdf_file_path)

page_num = 0
page = pdf_document[page_num]
page_text = page.get_text()

print(f"Content of Page 1:\n{page_text}")
pdf_document.close()


Content of Page 1:
 
1 
PALESTINE 
 
 
 
Introduction 
 
This report assesses the status of Palestinian women ten years after the Beijing Conference in the 
context of a survey of the Palestinian Authority’s achievements in the critical areas of concern of 
the Beijing Platform for Action. The report is the outcome of a joint cooperative effort on the 
part of the Ministry of Women’s Affairs and units concerned with issues of relevance for women 
in various other ministries. 
 
The preparation of this report comes at the time of a significant development in the history of 
mechanisms for the advancement of Palestinian women, namely the creation of a Ministry of 
Women’s Affairs within the current Palestinian Government as the main framework for the 
Government’s ongoing commitment to the empowerment of women and the unification of efforts 
directed toward that end, to quote from the new Ministry’s official mandate. 
 
We hope that this report will contribute to a greater understanding 

In [22]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp(page_text)

# Extract the first sentence
first_sentence = next(doc.sents, None)


if first_sentence:

    print(f"Original Sentence: {first_sentence.text}\n")

    # syntactic structure ,first sentence
    for token in first_sentence:
        print(f"Token: {token.text}, Dependency: {token.dep_}, Head: {token.head.text}, POS: {token.pos_}, Tag: {token.tag_}")
else:
    print("No sentences found in the content.")


Original Sentence:  
1 
PALESTINE 
 
 
 
Introduction 
 
This report assesses the status of Palestinian women ten years after the Beijing Conference in the 
context of a survey of the Palestinian Authority’s achievements in the critical areas of concern of 
the Beijing Platform for Action.

Token:  
, Dependency: dep, Head: 1, POS: SPACE, Tag: _SP
Token: 1, Dependency: nummod, Head: Introduction, POS: NUM, Tag: CD
Token: 
, Dependency: dep, Head: 1, POS: SPACE, Tag: _SP
Token: PALESTINE, Dependency: compound, Head: Introduction, POS: PROPN, Tag: NNP
Token: 
 
 
 
, Dependency: dep, Head: PALESTINE, POS: SPACE, Tag: _SP
Token: Introduction, Dependency: nsubj, Head: assesses, POS: NOUN, Tag: NN
Token: 
 
, Dependency: dep, Head: Introduction, POS: SPACE, Tag: _SP
Token: This, Dependency: det, Head: report, POS: DET, Tag: DT
Token: report, Dependency: nsubj, Head: assesses, POS: NOUN, Tag: NN
Token: assesses, Dependency: ROOT, Head: assesses, POS: VERB, Tag: VBZ
Token: the, Dependency: de

**Q5**

In [23]:
pdf_document = fitz.open(pdf_file_path)

# tokenize the text kol paga
for page_num in range(pdf_document.page_count):

    page = pdf_document[page_num]
    text = page.get_text()

    doc = nlp(text)

    # number of words
    word_count = sum(1 for token in doc if token.is_alpha)

    print(f"Page {page_num + 1}: {word_count} words")

pdf_document.close()


Page 1: 241 words
Page 2: 559 words
Page 3: 534 words
Page 4: 491 words
Page 5: 464 words
Page 6: 449 words
Page 7: 511 words
Page 8: 512 words
Page 9: 376 words
Page 10: 424 words
Page 11: 352 words
Page 12: 450 words
Page 13: 314 words
Page 14: 415 words
Page 15: 367 words
Page 16: 363 words
Page 17: 437 words
Page 18: 373 words
Page 19: 476 words
Page 20: 497 words
Page 21: 326 words
Page 22: 336 words
Page 23: 428 words
Page 24: 422 words
Page 25: 494 words
Page 26: 30 words
Page 27: 474 words
Page 28: 356 words
Page 29: 354 words
Page 30: 150 words


**Q6**

In [36]:
pdf_document = fitz.open(pdf_file_path)

# text of Page 1
page_num = 0  # Assuming you want to process Page 1
page = pdf_document[page_num]
text = page.get_text()

# Process the text using spaCy
doc = nlp(text)

# Eliminate stop words
filtered_words = [token.text for token in doc if not token.is_stop]
filtered_text = ' '.join(filtered_words)
word_count = len(filtered_words)
print(f"Number of words in the filtered text: {word_count}")


pdf_document.close()


Number of words in the filtered text: 156


In [37]:
#Text Cleaning Q7

In [38]:


# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Open the PDF document
pdf_document = fitz.open(pdf_file_path)

# Get the text of Page 1
page_num = 0  # Assuming you want to process Page 1
page = pdf_document[page_num]
text = page.get_text()

# Process the text using spaCy
doc = nlp(text)

# Eliminate stop words and print the remaining words
filtered_words = [token.text for token in doc if not token.is_stop]
filtered_text = ' '.join(filtered_words)

# Count the number of words in the filtered text
word_count = len(filtered_words)

# Print the text without stop words
print(f"Text of Page 1 without stop words:\n{filtered_text}")

# Print the number of words
print(f"Number of words in the filtered text: {word_count}")

# Close the PDF document
pdf_document.close()


Text of Page 1 without stop words:
 
 1 
 PALESTINE 
 
 
 
 Introduction 
 
 report assesses status Palestinian women years Beijing Conference 
 context survey Palestinian Authority achievements critical areas concern 
 Beijing Platform Action . report outcome joint cooperative effort 
 Ministry Women Affairs units concerned issues relevance women 
 ministries . 
 
 preparation report comes time significant development history 
 mechanisms advancement Palestinian women , creation Ministry 
 Women Affairs current Palestinian Government main framework 
 Government ongoing commitment empowerment women unification efforts 
 directed end , quote new Ministry official mandate . 
 
 hope report contribute greater understanding economic , social 
 political status Palestinian women identify current obstacles advancement 
 participation development process . hope decision - makers find useful 
 aid adopting measures policies aimed bridging gender gap . 
 
 Lastly , wish extend sincere thanks ap

**Q7**

In [43]:
import nltk
from nltk import word_tokenize
from nltk import pos_tag

# Sample text
text = """
PALESTINE

Introduction

This report assesses the status of Palestinian women years after the Beijing Conference
in the context of the survey of Palestinian Authority achievements in critical areas of concern
outlined in the Beijing Platform for Action. The report is the outcome of a joint cooperative effort
between the Ministry of Women Affairs and units concerned with issues relevant to women in various
ministries.

The preparation of this report comes at a significant point in the development history
of mechanisms for the advancement of Palestinian women, with the creation of the Ministry
of Women Affairs under the current Palestinian Government. It is the main framework for the
Government's ongoing commitment to the empowerment of women and unification efforts
directed towards this end, as stated in the new Ministry's official mandate.

We hope that this report contributes to a greater understanding of the economic, social,
and political status of Palestinian women, and helps identify current obstacles to their advancement
and participation in the development process. We also hope that decision-makers find it useful
in adopting measures and policies aimed at bridging the gender gap.

Lastly, we wish to extend our sincere thanks and appreciation to our women colleagues
in the units concerned with women's issues in various ministries for their invaluable assistance
in providing data and reports on their respective ministries' activities in this area.
"""

# Tokenize the text
tokens = word_tokenize(text)

# Perform POS tagging
pos_tags = pos_tag(tokens)

# Print the POS tags
for tag in pos_tags:
    print(tag)


('PALESTINE', 'NNP')
('Introduction', 'NNP')
('This', 'DT')
('report', 'NN')
('assesses', 'VBZ')
('the', 'DT')
('status', 'NN')
('of', 'IN')
('Palestinian', 'JJ')
('women', 'NNS')
('years', 'NNS')
('after', 'IN')
('the', 'DT')
('Beijing', 'NNP')
('Conference', 'NNP')
('in', 'IN')
('the', 'DT')
('context', 'NN')
('of', 'IN')
('the', 'DT')
('survey', 'NN')
('of', 'IN')
('Palestinian', 'JJ')
('Authority', 'NNP')
('achievements', 'NNS')
('in', 'IN')
('critical', 'JJ')
('areas', 'NNS')
('of', 'IN')
('concern', 'NN')
('outlined', 'VBN')
('in', 'IN')
('the', 'DT')
('Beijing', 'NNP')
('Platform', 'NNP')
('for', 'IN')
('Action', 'NNP')
('.', '.')
('The', 'DT')
('report', 'NN')
('is', 'VBZ')
('the', 'DT')
('outcome', 'NN')
('of', 'IN')
('a', 'DT')
('joint', 'JJ')
('cooperative', 'JJ')
('effort', 'NN')
('between', 'IN')
('the', 'DT')
('Ministry', 'NNP')
('of', 'IN')
('Women', 'NNP')
('Affairs', 'NNPS')
('and', 'CC')
('units', 'NNS')
('concerned', 'VBN')
('with', 'IN')
('issues', 'NNS')
('relevant

**Q8**

In [44]:
import fitz
from sklearn.feature_extraction.text import CountVectorizer


pdf_document = fitz.open(pdf_file_path)

# text of Page 1
page_num = 0  # Assuming you want to process Page 1
page = pdf_document[page_num]
text = page.get_text()

paragraphs = [p for p in text.split('\n') if p.strip()]

vectorizer = CountVectorizer()

# BOW model
bow_matrix = vectorizer.fit_transform(paragraphs)

feature_names = vectorizer.get_feature_names_out()

# BOW matrix
print("Bag-of-Words Matrix:")
print(bow_matrix.toarray())
print("\nFeature Names:")
print(feature_names)

# Close the PDF document
pdf_document.close()


Bag-of-Words Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 0]]

Feature Names:
['achievements' 'action' 'activities' 'adopting' 'advancement' 'affairs'
 'after' 'aid' 'aimed' 'all' 'also' 'and' 'appreciation' 'area' 'areas'
 'as' 'assesses' 'assistance' 'at' 'authority' 'beijing' 'bridging'
 'colleagues' 'comes' 'commitment' 'concern' 'concerned' 'conference'
 'context' 'contribute' 'cooperative' 'creation' 'critical' 'current'
 'data' 'decision' 'development' 'directed' 'economic' 'effort' 'efforts'
 'empowerment' 'end' 'extend' 'find' 'for' 'framework' 'from' 'gap'
 'gender' 'government' 'greater' 'history' 'hope' 'identify' 'in'
 'introduction' 'invaluable' 'is' 'issues' 'it' 'joint' 'lastly' 'main'
 'makers' 'mandate' 'measures' 'mechanisms' 'ministries' 'ministry'
 'namely' 'new' 'obstacles' 'of' 'official' 'on' 'ongoing' 'other' 'our'
 'outcome' 'palestine' 'palestinian' 'part' 'participation' 'platform

**Q9**

In [47]:
import fitz
from sklearn.feature_extraction.text import TfidfVectorizer


# Split the text into paragraphs based on newline character
paragraphs = [p for p in text.split('\n') if p.strip()]

# Initialize the TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Apply the TF-IDF model to the paragraphs
tfidf_matrix = tfidf_vectorizer.fit_transform(paragraphs)

# Get the feature names (words) in the TF-IDF model
feature_names = tfidf_vectorizer.get_feature_names_out()

# Print the TF-IDF matrix and feature names
print("TF-IDF Matrix:")
print(tfidf_matrix.toarray())
print("\nFeature Names:")
print(feature_names)



TF-IDF Matrix:
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.1416188  0.        ]
 [0.         0.         0.         ... 0.         0.18425777 0.        ]
 [0.         0.         0.30378974 ... 0.         0.         0.        ]]

Feature Names:
['achievements' 'action' 'activities' 'adopting' 'advancement' 'affairs'
 'after' 'aid' 'aimed' 'all' 'also' 'and' 'appreciation' 'area' 'areas'
 'as' 'assesses' 'assistance' 'at' 'authority' 'beijing' 'bridging'
 'colleagues' 'comes' 'commitment' 'concern' 'concerned' 'conference'
 'context' 'contribute' 'cooperative' 'creation' 'critical' 'current'
 'data' 'decision' 'development' 'directed' 'economic' 'effort' 'efforts'
 'empowerment' 'end' 'extend' 'find' 'for' 'framework' 'from' 'gap'
 'gender' 'government' 'greate

**Q10**
im using colab .. the size of glove is so large ..so i use the tf-idf

In [51]:
import spacy
from sklearn.metrics.pairwise import cosine_similarity

# Get the feature names (words) in the TF-IDF model
feature_names = tfidf_vectorizer.get_feature_names_out()

# Dictionary to store similar words for each word in the TF-IDF model
similar_words_dict = {}

# Find similar words for each word in the TF-IDF model
for word in feature_names:
    token = nlp(word)

    # Check if the word is in the spaCy vocabulary
    if token.has_vector:
        # Use spaCy's most_similar method to get similar words
        similar_words = [w for w in feature_names if w != word and cosine_similarity(tfidf_matrix[:, tfidf_vectorizer.vocabulary_[word]].reshape(1, -1), tfidf_matrix[:, tfidf_vectorizer.vocabulary_[w]].reshape(1, -1))[0][0] > 0.5]

        # Store similar words in the dictionary
        similar_words_dict[word] = similar_words

# Print similar words for each word in the TF-IDF model
for word, similar_words in similar_words_dict.items():
    print(f"Similar words for '{word}': {', '.join(similar_words)}")


Similar words for 'achievements': areas, authority, concern, context, critical, of, survey
Similar words for 'action': beijing, cooperative, effort, is, joint, on, outcome, platform
Similar words for 'activities': area, data, on, providing, reports, respective, their, us, with
Similar words for 'adopting': aid, aimed, at, bridging, gap, gender, measures, policies
Similar words for 'advancement': creation, identify, mechanisms, namely, obstacles, palestinian, political, status
Similar words for 'affairs': as, current, for, framework, government, main, part, relevance, within, women
Similar words for 'after': assesses, beijing, conference, report, status, ten, this, years
Similar words for 'aid': adopting, aimed, at, bridging, gap, gender, measures, policies
Similar words for 'aimed': adopting, aid, at, bridging, gap, gender, measures, policies
Similar words for 'all': appreciation, colleagues, extend, lastly, our, sincere, thanks, to, we, wish
Similar words for 'also': decision, develop